export const VALID_FONCTIONS = [
  "Acheteur-Approvisionneur",
  "Acheteur-Approvisionneur Principal",
  "Agent Administratif",
  "Assistant Administratif",
  "Assistant Support Informatique",
  "Cadre Administratif et de Gestion",
  "Cadre Contrôle Commande RT",
  "Cadre Exploitation Réseau",
  "Cadre HC",
  "Cadre Lignes THT&HT",
  "Cadre Postes THT/HT",
  "Cadre TST Lignes THT&HT",
  "Cadre Technique",
  "Cadre Télécom",
  "Chef d'Equipe Electromécanicien",
  "Chef d'Equipe Isolation Thermique",
  "Chef d'Equipe Lignes THT&HT",
  "Chef d'Equipe Postes THT/HT",
  "Chef de Division",
  "Chef de Service",
  "Conducteur Engins Spéciaux",
  "Conducteur Mécanicien",
  "Conducteur Principal de Direction",
  "Conducteur Travaux Génie Civil",
  "Contremaître Lignes THT&HT",
  "Contremaître Postes THT/HT",
  "Contremaître TST Lignes THT&HT",
  "Contremaître TST Postes THT/HT",
  "Contrôleur Travaux Génie Civil",
  "Documentaliste",
  "Employé de Bureau Principal",
  "Gestionnaire Ressources Humaines",
  "Monteur de Lignes THT&HT",
  "Opérateur TST Lignes THT&HT",
  "Opérateur TST Postes THT/HT",
  "Ouvrier Professionnel Réseau",
  "Préparateur Lignes MT&BT",
  "Projeteur Lignes THT&HT",
  "Secrétaire Principale",
  "Surveillant Travaux Génie Civil",
  "Technicien Contrôle Commande RT",
  "Technicien Exploitation Réseau",
  "Technicien Lignes THT&HT",
  "Technicien Ppal Contrôle Commande RT",
  "Technicien Principal Contrôle Commande RT",
  "Technicien Principal Exploitation Réseau",
  "Technicien Spécialisé Télécom",
] as const;

export type ValidFonction = (typeof VALID_FONCTIONS)[number];
