import { db } from "../db-pg";
import * as schema from "../schema";
import { eq } from "drizzle-orm";

// Auto-generated from Tableau_dHabilitations.xlsx — 309 employees
const CORRECT_NAMES: { matricule: string; nom: string; prenom: string }[] = [
  { matricule: "81921", nom: "Ibnas", prenom: "Soufiane" },
  { matricule: "78040", nom: "Elmouakit", prenom: "Abdelmalek" },
  { matricule: "81450", nom: "Ettafs", prenom: "Yassine" },
  { matricule: "78957", nom: "Baissa", prenom: "Youssef" },
  { matricule: "83172", nom: "Laouaj", prenom: "Mohamed" },
  { matricule: "79327", nom: "Oumoussi", prenom: "Ahmed" },
  { matricule: "75451", nom: "Rbaibi", prenom: "Mustapha" },
  { matricule: "78782", nom: "Bouregh", prenom: "Salah" },
  { matricule: "81920", nom: "Laroussi", prenom: "Salah" },
  { matricule: "82386", nom: "Lafroudi", prenom: "Mohammed" },
  { matricule: "79328", nom: "Aresmouk", prenom: "Soufiane" },
  { matricule: "79876", nom: "Chegdali", prenom: "Mohamed" },
  { matricule: "79953", nom: "Moro", prenom: "Abderrahim" },
  { matricule: "79411", nom: "Ait Oulaid", prenom: "Brahim" },
  { matricule: "76888", nom: "Quhila", prenom: "Khalid" },
  { matricule: "81135", nom: "Bouzougagh", prenom: "Momamed" },
  { matricule: "81523", nom: "Echakraoui", prenom: "Yassine" },
  { matricule: "80487", nom: "Chabih", prenom: "Badr" },
  { matricule: "78005", nom: "El Alji", prenom: "Rachid" },
  { matricule: "81628", nom: "Zraygue", prenom: "Mustapha" },
  { matricule: "78954", nom: "En-nour", prenom: "Abdessamad" },
  { matricule: "84632", nom: "Boughdir", prenom: "Abdelmonim" },
  { matricule: "84633", nom: "Ousbaa", prenom: "Imad-eddine" },
  { matricule: "79326", nom: "Bouri", prenom: "Abdeslam" },
  { matricule: "81155", nom: "Kacimi", prenom: "Naoufel" },
  { matricule: "79336", nom: "Ouhammou", prenom: "Jaouad" },
  { matricule: "79785", nom: "Boujamaoui", prenom: "Khalid" },
  { matricule: "79868", nom: "Talib", prenom: "Hicham" },
  { matricule: "78955", nom: "Monsif", prenom: "Rahal" },
  { matricule: "78958", nom: "Chahboune", prenom: "Khalid" },
  { matricule: "81813", nom: "Houssaini", prenom: "Mohamed" },
  { matricule: "79919", nom: "Chaouki", prenom: "Yassine" },
  { matricule: "82349", nom: "Elghafraoui", prenom: "Youness" },
  { matricule: "83192", nom: "Jamil", prenom: "Boutaina" },
  { matricule: "81933", nom: "El Korch", prenom: "Redouane" },
  { matricule: "82306", nom: "Erradi", prenom: "Othmane" },
  { matricule: "81582", nom: "Elmekaoui", prenom: "Mohamed" },
  { matricule: "83630", nom: "Ahttab", prenom: "Brahim" },
  { matricule: "83510", nom: "Noughira", prenom: "Samir" },
  { matricule: "74206", nom: "Moayed", prenom: "Abdelkrim" },
  { matricule: "84073", nom: "Rachidi", prenom: "Said" },
  { matricule: "81293", nom: "Dahaoui", prenom: "Youness" },
  { matricule: "82019", nom: "Et-talby", prenom: "Rachid" },
  { matricule: "82374", nom: "Laoudi", prenom: "Oussama" },
  { matricule: "82376", nom: "Mouradi", prenom: "Yassine" },
  { matricule: "83628", nom: "Ouaza", prenom: "Driss" },
  { matricule: "78952", nom: "El Assali", prenom: "Khalid" },
  { matricule: "80409", nom: "Lach-heb", prenom: "Youness" },
  { matricule: "80537", nom: "Loudy", prenom: "Hamid" },
  { matricule: "77687", nom: "Boumahta", prenom: "Abdelmajid" },
  { matricule: "78983", nom: "Kerouich", prenom: "Khalid" },
  { matricule: "81632", nom: "Obbiba", prenom: "Ouadyae" },
  { matricule: "80795", nom: "Rabbaj", prenom: "Driss" },
  { matricule: "79274", nom: "Boujmai", prenom: "Nabil" },
  { matricule: "79917", nom: "Jaha", prenom: "Mohamed" },
  { matricule: "80226", nom: "Bachar", prenom: "Mohamed" },
  { matricule: "84828", nom: "Gamil", prenom: "Youssef" },
  { matricule: "80228", nom: "Ouahabi", prenom: "Jalal" },
  { matricule: "80237", nom: "Beniffou", prenom: "Abdelkader" },
  { matricule: "82381", nom: "Khadraoui", prenom: "Mehdi" },
  { matricule: "80359", nom: "Lahkim", prenom: "Said" },
  { matricule: "80398", nom: "Zakhir", prenom: "El Hadj" },
  { matricule: "81913", nom: "Lachkar", prenom: "Ilyas" },
  { matricule: "83350", nom: "Babaissa", prenom: "Abderrahim" },
  { matricule: "82637", nom: "Saidi", prenom: "Khalid" },
  { matricule: "80345", nom: "Farichouch", prenom: "Hicham" },
  { matricule: "83407", nom: "El Faiz", prenom: "Cherki" },
  { matricule: "81011", nom: "Ed-douh", prenom: "Mourad" },
  { matricule: "81124", nom: "Almou", prenom: "Aziz" },
  { matricule: "81126", nom: "Mouimi", prenom: "Noureddine" },
  { matricule: "84630", nom: "Zegai", prenom: "Mohammed" },
  { matricule: "82262", nom: "Achlouj", prenom: "Salah-eddine" },
  { matricule: "79729", nom: "Aderdour", prenom: "Ismail" },
  { matricule: "80906", nom: "El Attari", prenom: "Yassine" },
  { matricule: "78234", nom: "Bamarjane", prenom: "Jamal" },
  { matricule: "75949", nom: "El Khaoua", prenom: "Rachid" },
  { matricule: "81129", nom: "Tanji", prenom: "Ilyass" },
  { matricule: "81134", nom: "Bouhafs", prenom: "El Mostafa" },
  { matricule: "84072", nom: "Elmakhloufy", prenom: "Abdejalil" },
  { matricule: "80460", nom: "Najidi", prenom: "Ahmed" },
  { matricule: "78987", nom: "Sadiki", prenom: "Younes" },
  { matricule: "80559", nom: "Raki", prenom: "Brahim" },
  { matricule: "82338", nom: "Idir", prenom: "Amine" },
  { matricule: "83527", nom: "Touiti", prenom: "Lahsen" },
  { matricule: "81594", nom: "Boukhriss", prenom: "Mohamed" },
  { matricule: "81997", nom: "Hakimi", prenom: "Youssef" },
  { matricule: "81998", nom: "Sayad", prenom: "Badr-eddine" },
  { matricule: "84957", nom: "Chaabi", prenom: "Rabia" },
  { matricule: "82363", nom: "Mouhoub", prenom: "Youness" },
  { matricule: "82400", nom: "Najid", prenom: "Hamza" },
  { matricule: "75980", nom: "Rouias", prenom: "Nacer" },
  { matricule: "74200", nom: "Lemrouaj", prenom: "Jilali" },
  { matricule: "76432", nom: "Ghalem", prenom: "Mohamed" },
  { matricule: "80045", nom: "Hamada", prenom: "Abdelhaq" },
  { matricule: "80227", nom: "Haj", prenom: "Brahim" },
  { matricule: "79276", nom: "Balhaddad", prenom: "Badre" },
  { matricule: "80489", nom: "Abbdellaoui", prenom: "Abdelati" },
  { matricule: "80533", nom: "Laissi", prenom: "Lotfi" },
  { matricule: "80793", nom: "Boulghait", prenom: "Mohamed" },
  { matricule: "80794", nom: "Abouamama", prenom: "Ahmed" },
  { matricule: "80924", nom: "El-moukh", prenom: "Said" },
  { matricule: "75453", nom: "Fareh", prenom: "Abderrahim" },
  { matricule: "81130", nom: "Larhzaoui", prenom: "Lahsen" },
  { matricule: "81132", nom: "Kahlaoui", prenom: "Moussa" },
  { matricule: "78934", nom: "Bahlouli", prenom: "Samir" },
  { matricule: "82304", nom: "Yousfi", prenom: "Abdelhaq" },
  { matricule: "78935", nom: "Allioui", prenom: "Rachid" },
  { matricule: "83258", nom: "Kajad", prenom: "Mahmoud" },
  { matricule: "81371", nom: "Bourakba", prenom: "Issam" },
  { matricule: "81125", nom: "Moudkiri", prenom: "Ayoub" },
  { matricule: "81907", nom: "Zoubir", prenom: "Mohamed" },
  { matricule: "82342", nom: "Moustaqim", prenom: "Youssef" },
  { matricule: "81522", nom: "Zerrad", prenom: "Karim" },
  { matricule: "80960", nom: "Bounhiza", prenom: "Abdelwahab" },
  { matricule: "81581", nom: "Kebdani", prenom: "Charaf" },
  { matricule: "81122", nom: "Bouali", prenom: "Yassine" },
  { matricule: "82617", nom: "Er-rached", prenom: "Imad" },
  { matricule: "81123", nom: "Bigourramen", prenom: "Hicham" },
  { matricule: "81814", nom: "Drawat", prenom: "Yassine" },
  { matricule: "81595", nom: "Gharib", prenom: "Abdelali" },
  { matricule: "81915", nom: "Sadouk", prenom: "Yassine" },
  { matricule: "82305", nom: "Ettayea", prenom: "Mostapha" },
  { matricule: "81640", nom: "Bouhachem", prenom: "Ilyass" },
  { matricule: "82620", nom: "Bakhouch", prenom: "Mohammed" },
  { matricule: "82641", nom: "Et-talaoui", prenom: "Mohamed" },
  { matricule: "80609", nom: "Moudkiri", prenom: "Hassan" },
  { matricule: "81752", nom: "Derrich", prenom: "El Mehdi" },
  { matricule: "82794", nom: "Zeriat", prenom: "El Mahdi" },
  { matricule: "83518", nom: "Marrous", prenom: "Yahya" },
  { matricule: "83520", nom: "Aakrach", prenom: "Abdelhak" },
  { matricule: "74210", nom: "Saif", prenom: "Mohamed" },
  { matricule: "79033", nom: "Benrahhou", prenom: "Abdelmajid" },
  { matricule: "82623", nom: "Mabrouka", prenom: "Mouhssine" },
  { matricule: "76509", nom: "Mesrar", prenom: "Rachid" },
  { matricule: "84833", nom: "Hachlaf", prenom: "Rachid" },
  { matricule: "85859", nom: "El Gharmah", prenom: "Ali" },
  { matricule: "79848", nom: "Idrissi Bourhim", prenom: "Said" },
  { matricule: "83083", nom: "Bouchtaoui", prenom: "Jamal-eddine" },
  { matricule: "81990", nom: "Toubali", prenom: "Youssef" },
  { matricule: "76988", nom: "Ougil", prenom: "Hamid" },
  { matricule: "80532", nom: "Torabi", prenom: "Ahmed" },
  { matricule: "81999", nom: "El Aouja", prenom: "Abdessamad" },
  { matricule: "83506", nom: "Oubourou", prenom: "Ider" },
  { matricule: "82094", nom: "Boussif", prenom: "El Kbir" },
  { matricule: "79920", nom: "Alami Qammouri", prenom: "Abdellah" },
  { matricule: "82302", nom: "Halloumi", prenom: "Abelali" },
  { matricule: "83509", nom: "Laroui", prenom: "Omar" },
  { matricule: "83635", nom: "Amzil", prenom: "Kamal" },
  { matricule: "83513", nom: "Siham", prenom: "Jabir" },
  { matricule: "82307", nom: "Abad", prenom: "Hamza" },
  { matricule: "82315", nom: "Eddahbi", prenom: "Hicham" },
  { matricule: "82316", nom: "Ghazi", prenom: "Hassan" },
  { matricule: "83516", nom: "Aziz", prenom: "Mohamed" },
  { matricule: "80610", nom: "Saib", prenom: "Talal" },
  { matricule: "83519", nom: "Zouaghi", prenom: "Mohamed" },
  { matricule: "83593", nom: "Oulhaj", prenom: "Daid" },
  { matricule: "84066", nom: "Elbir", prenom: "Mehdi" },
  { matricule: "82351", nom: "Samih", prenom: "Mustapha" },
  { matricule: "74338", nom: "Mourafi", prenom: "Bouchaib" },
  { matricule: "80438", nom: "Naouni", prenom: "Mohamed" },
  { matricule: "80792", nom: "Lamkhartat", prenom: "Rida" },
  { matricule: "75537", nom: "Houboub", prenom: "Khalid" },
  { matricule: "79661", nom: "Larhzil", prenom: "Fatima" },
  { matricule: "75447", nom: "Moustakim", prenom: "Abdelhak" },
  { matricule: "83625", nom: "Madani", prenom: "Abdelkabir" },
  { matricule: "83756", nom: "Jeddi", prenom: "Moncef" },
  { matricule: "83945", nom: "Idrissi", prenom: "Amine" },
  { matricule: "82513", nom: "El Hajji", prenom: "Outmane" },
  { matricule: "84706", nom: "Bellaouali", prenom: "Abdelilah" },
  { matricule: "84714", nom: "Erradi", prenom: "Abdelilah" },
  { matricule: "81131", nom: "El Bachouri", prenom: "Yassine" },
  { matricule: "83143", nom: "Ait Kaddour", prenom: "Moncef" },
  { matricule: "82337", nom: "Ounir", prenom: "Abdelatif" },
  { matricule: "84817", nom: "Ait Dassar", prenom: "Hamza" },
  { matricule: "82649", nom: "Benzazaa", prenom: "Yassine" },
  { matricule: "84827", nom: "Mostakim", prenom: "Othmane" },
  { matricule: "82743", nom: "Itbane", prenom: "Abdelqodouss" },
  { matricule: "85497", nom: "Youness", prenom: "Ahmed" },
  { matricule: "82733", nom: "Boumja", prenom: "Youssef" },
  { matricule: "85666", nom: "Aiachi Mohammed", prenom: "Amine" },
  { matricule: "83511", nom: "Ait Alla", prenom: "Mohamed" },
  { matricule: "80491", nom: "Lakmas", prenom: "Mhamed" },
  { matricule: "85844", nom: "Haouli", prenom: "Yassine" },
  { matricule: "85886", nom: "Kara", prenom: "Jihad" },
  { matricule: "85888", nom: "El Harrak", prenom: "Yassine" },
  { matricule: "81208", nom: "Errabbaa", prenom: "Youssef" },
  { matricule: "81521", nom: "Hamriti", prenom: "Abdelhak" },
  { matricule: "80811", nom: "Garbi", prenom: "Redouane" },
  { matricule: "84818", nom: "Khanaoui", prenom: "El Mehdi" },
  { matricule: "81014", nom: "Said", prenom: "Noureddine" },
  { matricule: "85263", nom: "Touti", prenom: "Zahra" },
  { matricule: "82682", nom: "Belaabidia", prenom: "Oussama" },
  { matricule: "81763", nom: "Bentalha", prenom: "Hajar" },
  { matricule: "74608", nom: "Khalil", prenom: "Mustapha" },
  { matricule: "83505", nom: "Amimi", prenom: "Mohamed" },
  { matricule: "82552", nom: "Mouchtaki", prenom: "Youssef" },
  { matricule: "85908", nom: "Kounine", prenom: "Rida" },
  { matricule: "81133", nom: "Ouballa", prenom: "Aissam" },
  { matricule: "84084", nom: "Baba", prenom: "Ayoub" },
  { matricule: "81585", nom: "Echtouki", prenom: "Abdelhadi" },
  { matricule: "82624", nom: "Nossir", prenom: "Messaoud" },
  { matricule: "84487", nom: "Ahla", prenom: "Ammar" },
  { matricule: "84821", nom: "Ennadir", prenom: "Amine" },
  { matricule: "81802", nom: "Nfaoui", prenom: "Badre" },
  { matricule: "83249", nom: "Laanaya", prenom: "Ahmed" },
  { matricule: "81205", nom: "Nouga", prenom: "Omar" },
  { matricule: "83512", nom: "Ibhioun", prenom: "Aziz" },
  { matricule: "83517", nom: "Belkrafi", prenom: "Mohammed" },
  { matricule: "84741", nom: "Jamali", prenom: "Mounir" },
  { matricule: "84949", nom: "Chaif", prenom: "Nour-eddine" },
  { matricule: "83559", nom: "Zouine", prenom: "Said" },
  { matricule: "83064", nom: "Filali-ansari", prenom: "Mustapha" },
  { matricule: "85072", nom: "Mountahi", prenom: "Amine" },
  { matricule: "83601", nom: "Madda", prenom: "Tarik" },
  { matricule: "81584", nom: "Janah", prenom: "Zakaria" },
  { matricule: "83626", nom: "Khalid", prenom: "Abdeslam" },
  { matricule: "83526", nom: "Aassaoui", prenom: "Abdelhalim" },
  { matricule: "84716", nom: "Mirhlami", prenom: "Mohammed" },
  { matricule: "83629", nom: "Benrabeh", prenom: "Abdelah" },
  { matricule: "81157", nom: "Dakir", prenom: "Houssam" },
  { matricule: "81657", nom: "Goual", prenom: "Yassine" },
  { matricule: "85045", nom: "Errami", prenom: "Noureddin" },
  { matricule: "85945", nom: "Errifai", prenom: "Mohamed" },
  { matricule: "83515", nom: "Falaki", prenom: "Abdelilah" },
  { matricule: "84003", nom: "Atti", prenom: "Hamza" },
  { matricule: "84005", nom: "Bouchlaghem", prenom: "Badre" },
  { matricule: "84981", nom: "Ech-chaouqi", prenom: "Abdessamad" },
  { matricule: "79350", nom: "Damouche", prenom: "Abderrahim" },
  { matricule: "83300", nom: "El Hrychy", prenom: "Oussama" },
  { matricule: "83524", nom: "Gouhna", prenom: "Abdessamad" },
  { matricule: "83521", nom: "Boujdig", prenom: "Youssef" },
  { matricule: "84071", nom: "Haffar", prenom: "El Mostafa" },
  { matricule: "81274", nom: "El Ouadyly", prenom: "Abderrahim" },
  { matricule: "81366", nom: "Azzou", prenom: "Hamid" },
  { matricule: "81914", nom: "Akrim", prenom: "Amine" },
  { matricule: "81431", nom: "Boucetta", prenom: "Youssef" },
  { matricule: "84743", nom: "Ait Labsir", prenom: "Ayman" },
  { matricule: "84742", nom: "Chahboun", prenom: "M'barek" },
  { matricule: "84606", nom: "Chajai", prenom: "Ayoub" },
  { matricule: "84352", nom: "Rahali", prenom: "Ali" },
  { matricule: "85352", nom: "Mir", prenom: "Nabil" },
  { matricule: "85659", nom: "El Azzab", prenom: "Bouchra" },
  { matricule: "84676", nom: "Elhamrit", prenom: "Zakaria" },
  { matricule: "85690", nom: "Benayachy", prenom: "Khalid" },
  { matricule: "84683", nom: "Bakhouya", prenom: "Mohamed" },
  { matricule: "84705", nom: "Fandoul", prenom: "Mohamed" },
  { matricule: "80925", nom: "Zouita", prenom: "Najib" },
  { matricule: "84713", nom: "Jabnaoui", prenom: "Otmane" },
  { matricule: "82323", nom: "Misbah", prenom: "Amal" },
  { matricule: "82472", nom: "Gassir", prenom: "Nabila" },
  { matricule: "83835", nom: "Maghni", prenom: "Kamal" },
  { matricule: "84063", nom: "Saabane", prenom: "Hanane" },
  { matricule: "84490", nom: "Najjari", prenom: "Baderddine" },
  { matricule: "84751", nom: "Kabyl", prenom: "Yassine" },
  { matricule: "84752", nom: "Zantoute", prenom: "Kamal" },
  { matricule: "85495", nom: "Zeroual Mohamed", prenom: "Amine" },
  { matricule: "85496", nom: "Zahir", prenom: "Hamza" },
  { matricule: "81973", nom: "Chhiba", prenom: "Abdelghafour" },
  { matricule: "82738", nom: "Bensaada", prenom: "El Mokhtar" },
  { matricule: "82810", nom: "Elmazgui", prenom: "Youssef" },
  { matricule: "80536", nom: "Hammat", prenom: "Hayat" },
  { matricule: "83627", nom: "Elkarfi", prenom: "Tariq" },
  { matricule: "84876", nom: "Lambarki", prenom: "Abderrahim" },
  { matricule: "85872", nom: "Benelmekroud", prenom: "Hicham" },
  { matricule: "84822", nom: "Zilaf", prenom: "Youssef" },
  { matricule: "85941", nom: "Ourchid", prenom: "Mohammed" },
  { matricule: "85978", nom: "Hamouch", prenom: "Hamza" },
  { matricule: "81367", nom: "Aoultum", prenom: "Mohamed" },
  { matricule: "77889", nom: "Hassoune", prenom: "Abderrazak" },
  { matricule: "81107", nom: "Hifdi", prenom: "Azzeddine" },
  { matricule: "84923", nom: "Aouad", prenom: "Mouad" },
  { matricule: "82446", nom: "Errouissi", prenom: "Mohammed" },
  { matricule: "83781", nom: "El Jaafari", prenom: "Rachid" },
  { matricule: "84820", nom: "Kassimi", prenom: "Tarik" },
  { matricule: "85023", nom: "Faris", prenom: "Ayoub" },
  { matricule: "85024", nom: "Falouss", prenom: "Bassam" },
  { matricule: "85031", nom: "Essaif", prenom: "Hamza" },
  { matricule: "80922", nom: "Chibane", prenom: "Zakaria" },
  { matricule: "84682", nom: "Hassoum", prenom: "Abdellatif" },
  { matricule: "85083", nom: "Ouassiri", prenom: "Said" },
  { matricule: "78402", nom: "Ez-zouine", prenom: "El Mostafa" },
  { matricule: "78286", nom: "El Alami", prenom: "Sabir" },
  { matricule: "84715", nom: "Tidaf", prenom: "Younes" },
  { matricule: "84717", nom: "Lsfer", prenom: "Outmane" },
  { matricule: "76759", nom: "Laarissi", prenom: "Abdeslam" },
  { matricule: "85637", nom: "Ennajah", prenom: "Marouane" },
  { matricule: "78849", nom: "Nabili", prenom: "Moubarik" },
  { matricule: "85660", nom: "Boulal", prenom: "Hamza" },
  { matricule: "85664", nom: "Fattah", prenom: "Hassan" },
  { matricule: "85665", nom: "Morhli", prenom: "Marouane" },
  { matricule: "81670", nom: "Said", prenom: "Zouhair" },
  { matricule: "82450", nom: "Chamsi", prenom: "Abdesslam" },
  { matricule: "84002", nom: "Qraitich", prenom: "Mohamed" },
  { matricule: "79677", nom: "El Bouyahyaoui", prenom: "Mustapha" },
  { matricule: "84004", nom: "Elwardi", prenom: "Zouheïr" },
  { matricule: "84816", nom: "Outaarabt", prenom: "Ayoub" },
  { matricule: "85863", nom: "Ahmiche", prenom: "Abdellatif" },
  { matricule: "85865", nom: "Eritali", prenom: "Ahmed" },
  { matricule: "84819", nom: "El Idrissi", prenom: "Anouar" },
  { matricule: "82622", nom: "Jarane", prenom: "Zouhair" },
  { matricule: "85887", nom: "Latrache", prenom: "Mohamed" },
  { matricule: "83571", nom: "Jabri", prenom: "Abdelali" },
  { matricule: "82848", nom: "Mojahid", prenom: "Reda" },
  { matricule: "85939", nom: "Ouallal", prenom: "Amine" },
  { matricule: "84881", nom: "Naamy", prenom: "Said" },
  { matricule: "85860", nom: "Dnaya", prenom: "Abdelghafour" },
  { matricule: "85862", nom: "Arche", prenom: "Azzeddine" },
  { matricule: "96277", nom: "Toniyos", prenom: "Ahmed" },
  { matricule: "96280", nom: "Barouch", prenom: "Mohamed" },
];

export async function runNamesMigration(): Promise<void> {
  let fixed = 0;
  for (const entry of CORRECT_NAMES) {
    try {
      const rows = await db
        .select({ id: schema.employees.id })
        .from(schema.employees)
        .where(eq(schema.employees.matricule, entry.matricule))
        .limit(1);
      if (rows.length === 0) continue;
      await db
        .update(schema.employees)
        .set({ nom: entry.nom, prenom: entry.prenom })
        .where(eq(schema.employees.id, rows[0].id));
      fixed++;
    } catch { /* skip */ }
  }
  if (fixed > 0) console.log("[migration] Fixed " + fixed + " employee names");
}
